= Go Interfaces
:page-tags: go interface implementation struct method oop
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Intro

The goal of this document is to capture some of the main, important ideas about Go interfaces, some use cases, examples and explanations.

[NOTE]
====
We'll use the terms function and method interchangeably in the following text to avoid being repetitive or too verbose when explaining certain ideas.

For example, instead of saying things like “given a function _or_ method that takes an ``io.Writer``...”, we'll simply say “given a function that takes an ``io.Writer``...”.
====

== io.Writer

This is the interface `io.Writer` as of Go 1.24.0 in 2025:

[source,go]
----
// Writer is the interface that wraps the basic Write method.
//
// Write writes len(p) bytes from p to the underlying data stream.
// It returns the number of bytes written from p (0 <= n <= len(p))
// and any error encountered that caused the write to stop early.
// Write must return a non-nil error if it returns n < len(p).
// Write must not modify the slice data, even temporarily.
//
// Implementations must not retain p.
type Writer interface {
	Write(p []byte) (n int, err error)
}
----

Let's take a look at some useful types that satisfy the `io.Writer` interface.

=== slog.NewTextHandler()

`slog.NewTextHandler()` takes an `io.Writer` as its first parameter, and `os.Stdout` fits the bill:

[source,go]
----
logger := slog.New(slog.NewTextHandler(os.Stdout, nil))
----


++++
<style type="text/css" rel="stylesheet">
body {
  font-family: Ubuntu, 'Noto Sans', 'Open Sans', Helvetica, Arial;
}

.hljs-comment,
pre.pygments .tok-c1 {
  font-style: normal;
}
</style>
++++
