= Percentages | Math
:page-tags: math percentages
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Introduction

In these examples we will use:

* stem:[p] to represent the percent.
* stem:[b] to represent the base or quantity.
* stem:[n] to represent the percentage.

== Find percentage of a quantity

=== Example 1

What is 25% of 60? We know 25 the percent stem:[p], 60 is the base stem:[b], and we want to find the percentage stem:[n].

Then, the formula is:

[stem]
++++
\frac{n}{100} \times {x} = p
++++

Substituting and solving:

* stem:[\frac{25}{100}\times{60}=p]
* stem:[0.25\times{60}=p]
* stem:[15=p]

Therefore, 25% of 60 is 15, or 15 is 25% of 60.

== Find the percent or ratio

=== Example 1

15 is what percent of 60?

We know that the percentage stem:[n] is 15, and that the base or quantity stem:[b] is 60.
We want to find percent stem:[p].

Then, the formula is:

[stem]
++++
\frac{n}{b}\times{100} = p
++++

Substituting and solving:

* stem:[\frac{15}{60}\times{100} = p]
* stem:[0.25\times{100} = p]
* stem:[25 = p]

Therefore, 15 is 25% of 60.

== Find the quantity from a percentage and percent

15 is 25% of what quantity?

We know the percentage stem:[n] is 15, and that the percent stem:[p]
is 25.
We want to find the base (or quantity) stem:[b].

The formula is:

[stem]
++++
\frac{n}{p}\times{100} = b
++++

Substituting and solving:

* stem:[\frac{15}{25}\times{100} = b]
* stem:[0.6\times{100} = b]
* stem:[60 = b]

Therefore, 15 is 25% of 60.

++++
<style type="text/css" rel="stylesheet">
body {
  font-family: Ubuntu, 'Noto Sans', 'Open Sans', Helvetica, Arial;
}

.hljs-comment,
pre.pygments .tok-c1 {
  font-style: normal;
}
</style>
++++
