= SSH
:page-subtitle: Secure Shell
:page-tags: ssh openssh shell unix network
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Generate Private/Public Pair

`ssh-keygen` generates files in `$PWD`, and creates two files:
`id_<keytype>` and `id_<keytype>.pub`.
`-f` can be used to specify the output filename:

Nowadays (2024 as of this writing), ed25519 is the recommended type.

[quote, gitlab docs]
____
The book link:https://leanpub.com/gocrypto/read#leanpub-auto-chapter-5-digital-signatures[Practical Cryptography With Go^] suggests that link:https://ed25519.cr.yp.to/[ED25519^] keys are more secure and performant than RSA keys.

OpenSSH 6.5 introduced ED25519 SSH keys in 2014, and they should be available on most operating systems.

— https://docs.gitlab.com/ee/user/ssh.html#ed25519-ssh-keys
____

[source,bash]
----
$ ssh-keygen \
    -t ed25519 \
    -f ~/.ssh/id_my-project \
    -C 'email@example.dev'
----

Or if you need some older algorithm, like RSA, then something like this should also work:

[source,example]
----
$ ssh-keygen \
    -t rsa \
    -b 4096 \
    -f ~/.ssh/id_my-project
    -C 'email@example.dev'
----

* The public key is generated with the `.pub` filename extension.
  This one is the one you add to Gitlab, Github, or any server you want to log into with your local, private key.
* The private key has no extension.
  Never upload this file to server, never publish it anywhere.
  Store it safely.

Also, keys must have correct permissions (these are correct):

[source,example]
----
$ ls -l $HOME/.ssh
total 36
-rw-r--r-- 1 deveng deveng    65 Aug  8  2017 config
-r-------- 1 deveng deveng  1675 Mar 28  2017 id_rsa
-rw-r--r-- 1 deveng deveng   408 Mar 28  2017 id_rsa.pub
-rw------- 1 deveng deveng  3243 Apr  6 12:41 id_my-project-rsa-4096bits
-rw-r--r-- 1 deveng deveng   743 Apr  6 12:41 id_my-project-rsa-4096bits.pub
-rw-r--r-- 1 deveng deveng 13662 Apr  5 15:41 known_hosts
----

=== References

* link:https://docs.gitlab.com/ee/user/ssh.html[SSH Docs on Gitlab^].
* link:https://docs.github.com/en/authentication/connecting-to-github-with-ssh[SSH Docs on Github^].

== upload public key

You will have to provide the ssh password at least this once:

[source,example]
----
$ ssh-copy-id -i ~/·ssh/id_mykey.pub user@host
----

The above command will add your pub key contents to the end of `/home/youruser/.ssh/authorized_keys` on the server.

If `~/.ssh/authorized_keys` does not exist on the server, create it (empty file) and set the correct permissions:

[source,example]
----
chmod 744 ~/.ssh
chmod 600 ~/.ssh/authorized_keys
----

If permissions are two permissive, ssh won't work (neither if it is all 000).

== rsync with key auth

After you have your pub key on the server:

[source,example]
----
rsync -e 'ssh -i ~/.ssh/id_my-project' \
    --include-from=./upload-patterns-site.txt \
    ./ \
    myuser@mycompany.myserver.net:~/public_html/
----

== rsync with key auth and ~/.ssh/config

If you have your server set in `~/.ssh/config`, like

[source,example]
----
Host my-project
  IdentityFile ~/.ssh/id_workservers
  Port 22
  User myuser
  HostName mycompany.myserver.net
----

Then you can use `my-project` as the host argument for rsync:

[source,example]
----
rsync -e 'ssh -i ~/.ssh/id_my-project' \
    --include-from=./upload-patterns-site.txt \
    ./ \
    my-project:~/public_html/
----

== Git repo with specific SSH key

Basically, we want to map a URL of something like:

[source,example]
----
git@gitlab.com:deveng/memoapp.git
----

to:

[source,example]
----
git@myproj:deveng/memoapp.git
----

And _myproj_ is an entry config in `~/.ssh/config` which points to Gitlab.
It works with any server, not only Gitlab, because it is actually an SSH thing.

[source,example]
----
$ ssh-keygen \
-t rsa \
    -b 4096 \
    -C 'some-user@some-company.com' \
    -f ~/.ssh/id_some-user-some-company
----

Copy the contents of the public key:

[source,example]
----
$ xclip -sel clip < ~/.ssh/id_some-user-some-company.pub
----

Search for “SSH Keys” or something similar on your Gitlab profile settings and add the PUBLIC (never the private) key.

Suppose this is the repo:

[source,example]
----
git@gitlab.myproj.com:mycompany/memoapp.git
----

Replace `gitlab.myproj.com` with the name of your entry (the string after `Host`) on `~/.ssh/config`.

[source,example]
----
$ cat ~/.ssh/config
Host gitlab-awesome-project
  Hostname gitlab.myproj.com
  User git
  IdentityFile ~/.ssh/id_some-user-some-company
----

See:

[source,example]
----
$ git clone \
    git@gitlab-awesome-project:mycompany/myproj.git \
    --origin=gl

$ cd myproj

$ git remote -v
gl    git@gitlab-awesome-project:mycompany/myproj.git (fetch)
gl    git@gitlab-awesome-project:mycompany/myproj.git (push)
----
