= Builder | Creational Patterns
:page-subtitle: Design Patterns
:page-tags: design-patterns builder creational
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:source-highlighter: highlight.js
:experimental:
:stem: latexmath
:toc: left
:imagesdir: __assets
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== The Builder creational pattern

[quote]
____
Separate the construction of a complex object from its representation so that
the same construction process can create different representations.
____

The builder pattern helps construct complex objects without having to explicitly instantiate its values or writing the entire logic they require.
And we don't want to force consumers of those objects to have to do all that setup.

Object creation can be really simple, with default values, or complex if an object needs results from network requests, state checks, create nested objects for certain fields, etc.

== Director

Some resources pass the concrete builder implementation when an instance of the director is created, others when the `build()` method is called:

[source,text]
----
Director director = new Director(new SomeConcreteBuilder())
director.build()

// vs

Director director = new Director()
director.build(new SomeConcreteBuilder())
----

== Vehicle example

.Builder
[mermaid]
....
---
config:
  look: handDrawn
  theme: neutral
---

classDiagram

class Builder {
  <<interface>>
  + void addWheels(int numWheels)
  + int getVehicle()
}

class CarBuilder {
  - Car car
  + setWheels(int numWheels) void
  + setDoors(int numDors)
  + getVehicle() Vehicle
}

class TruckBuilder {
  - Car car
  + addWheels(int numWheels) void
  + getVehicle() Vehicle
}

CarBuilder <|.. Builder
TruckBuilder <|.. Builder
....

.Products
[mermaid]
....
classDiagram

class Car {
  - short numWheels
  - short numDoors
  + void addWheels(int qty)
  + int getWheels()
}
....

.Director
[mermaid]
....
classDiagram

class Director {
  + Director(builder Builder)
  + getVehicle() Vehicle
}

Director *--> Builder
....
