= Backup and Restore in PostgreSQL
:page-subtitle: PostgreSQL
:description: Some useful commands to create and manage roles (users), databases and tables in PostgreSQL.
:page-tags: dbsql database sql postgresql backup dump restore docker cmdline bash shell
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

.PG example user
[TIP]
====
Many of these examples use a role (user) called *devel*.
====


== Intro Notes

`pg_dump` can dump data in a few different formats.
SQL (plain text) dump output must be fed back into `psql`.
The “other formats” should be fed to `pg_restore`.

Also:

[quote, pg_dump v16 docs]
____
It is not guaranteed that ``pg_dump``'s output can be loaded into a server of an older major version — not even if the dump was taken from a server of that version.
Loading a dump file into an older server may require manual editing of the dump file to remove syntax not understood by the older server.

-- link:https://www.postgresql.org/docs/current/app-pgdump.html[pg_dump v15 docs^]
____


== From local database

Dump a local database in plain text (SQL) format:

[source,shell-session]
----
$ pg_dump -U devel -W -C -Fp mydb -f mydb.sql
----

Import a plain text (SQL) dump:

[source,shell-session]
----
psql -U devel -d mydb -f _stuff/mydb.sql
----

Restore a Heroku Postgres dump:

[source,shell-session]
----
$ pg_restore -U devel -d mydb mydb.backup
----

== From Docker Container

One approach is to use `pg_dump` from the host system (if available on the host system).

[source,shell-session]
----
$ pg_dump -h <host> -U <user> -C -Fp mydb --file ./mydb.sql
----

But if `pg_dump` version is older than the one on the server, it will refuse to try to dump the data from a newer version, or some other incompatibilities (see pg_dump docs).
If it is newer, it could introduce syntax and options that would then fail to be fed back to a server running an older version, thus requiring manual fixes on the dumped SQL.

Therefore, we can use `docker exec` and dump the database using the container’s version of `pg_dump`.
This way, `pg_dump` does NOT need to be installed on the host machine and it will certainly match the version of the PostgreSQL server running on the container, reducing the likelihood of problems and incompatibilities.

[source,shell-session]
----
$ docker exec my-pg-container pg_dump --version
pg_dump (PostgreSQL) 14.8 (Debian 14.8-1.pgdg120+1)
----

So, we can do something like this:

[source,shell-session]
----
$ docker exec my-pg-container \
    pg_dump -U dev -C -Fp mydb \
    | tee ./mydb.sql
----

We could also replace the _pipe_ and `tee` with a redirection:

[source,shell-session]
----
$ docker exec my-pg-container \
    pg_dump -U devel -C -Fp mydb \
    > ./mydb.sql
----

[NOTE]
====
DO NOT use the `-it` `docker exec` options.
Those are used if you want an interactive terminal/shell session with the running container, but here, we just want a non-interactive terminal to dump the database and pipe it to a file on the host machine.

If you use them (specifically `-t`), it will insert pseudo tty bytes into the output, potentially corrupting it.
I observed, for example, that it was causing CRLF line terminators being inserted into the dumped `.sql` files.
Because Docker runs Linux, and my local desktop was Arch Linux, that was not expected.
PostgreSQL inside the container should be using standard Linux newlines (`\n`, or linefeed, or 0x0a) for line terminators, not `\r\n` Windows line terminators.
====

To import from the local system into PostgreSQL running inside docker, first mount a volume mapping the local DB dumps into the container:

[source,yaml]
----
services:
  db:
    image: postgres:16
    container_name: postgresql-playground
    restart: always
    env_file: .env
    volumes:
      - "pg_db_data:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./dbdumps/:/dbdumps"
----

Then run a command like this:

[source,bash]
----
$ docker exec postgresql-playground \
    psql \
      -U dev \
      -d dev \
      -f /dbdumps/mydbdump.sql
----
