= Animal Magic
:page-subtitle: Exercism Go
:page-tags: exercism go random
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

Welcome to Animal Magic on Exercism's Go Track.
If you need help running the tests or submitting your code, check out `HELP.adoc`.
If you get stuck on the exercise, check out `HINTS.adoc`, but try and solve it without using those first :)

== Introduction

Package https://pkg.go.dev/math/rand[math/rand] provides support for generating pseudo-random numbers.

Here is how to generate a random integer between `0` and `99`:

[,go]
----
n := rand.Intn(100) // n is a random int, 0 <= n < 100
----

Function `rand.Float64` returns a random floating point number between `0.0` and `1.0`:

[,go]
----
f := rand.Float64() // f is a random float64, 0.0 <= f < 1.0
----

There is also support for shuffling a slice (or other data structures):

[,go]
----
x := []string{"a", "b", "c", "d", "e"}
// shuffling the slice put its elements into a random order
rand.Shuffle(len(x), func(i, j int) {
	x[i], x[j] = x[j], x[i]
})
----

== Seeds

The number sequences generated by package `math/rand` are not truly random.
Given a specific "seed" value, the results are entirely deterministic.

In Go 1.20+ the seed is automatically picked at random so you will see a different sequence of random numbers each time you run your program.

In prior versions of Go, the seed was `1` by default.
So to get different sequences for various runs of the program, you had to manually seed the random number generator, e.g.
with the current time, before retrieving any random numbers.

[,go]
----
rand.Seed(time.Now().UnixNano())
----

== Instructions

Elaine is working on a new children's game that features animals and magic wands.
It is time to code functions for rolling a die, generating random wand energy and shuffling a slice.

== 1. Roll a die.

Implement a `RollADie` function.

This will be the traditional twenty-sided die with numbers 1 to 20.

[,go]
----
d := RollADie() // d will be assigned a random int, 1 <= d <= 20
----

== 2. Generate wand energy.

Implement a `GenerateWandEnergy` function.
The wand energy should be a random floating point number equal or greater than 0.0 and less than 12.0.

[,go]
----
f := GenerateWandEnergy()  // f will be assigned a random float64, 0.0 <= f < 12.0
----

== 3. Shuffle a slice.

The game features eight different animals:

* ant
* beaver
* cat
* dog
* elephant
* fox
* giraffe
* hedgehog

Write a function `ShuffleAnimals` that returns a slice with the eight animals in random order.

== Source

=== Created by

* @norbs57

=== Contributed to by

* @junedev

== Solution

[source,go]
----
import (
	"math/rand"
)

// RollADie returns a random int d with 1 <= d <= 20.
func RollADie() int {
	n := rand.Intn(20)

	if n == 0 {
		return n + 1
	}

	return n
}

// GenerateWandEnergy returns a random float64 f with 0.0 <= f < 12.0.
func GenerateWandEnergy() float64 {
	return rand.Float64() * 12
}

// ShuffleAnimals returns a slice with all eight animal strings in
// random order.
func ShuffleAnimals() []string {
	animals := []string{
		"ant",
		"beaver",
		"cat",
		"dog",
		"elephant",
		"fox",
		"giraffe",
		"hedgehog",
	}

	rand.Shuffle(len(animals), func(i, j int) {
		animals[i], animals[j] = animals[j], animals[i]
	})

	return animals
}
----
