= Number Line Jumps (Kangaroo)
:page-subtitle: HackerRank
:page-tags: hackerrank algorithm loop math
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

tags: hackerrank algorithm number loop math formula

* link:https://www.hackerrank.com/challenges/kangaroo/problem[Number Line Jumps (Kangaroo) challenge on HackerRank^].

At after some number of jumps, they either get to the same location (return "YES"), or they exceed the number of jumps and never get to the same location together (return "NO").

The kangaroos will both perform the same number of jumps.
One kangaroo cannot perform more or less jumps than the other.

One of the constraints states that the second kangaroos start position will always be greater than the first kangaroo.
That is, the first kangaroo always starts behind the second, and the second kangaroo always starts ahead of the first.

== JavaScript

=== Solution 1 with a loop

This solution involves looping through the jumps to test if we can arrive at the same location at some point.

Because it uses a loop, it has T.C stem:[O(1)].

[source,javascript]
----
const MAX_ITERATIONS = 1e4;

/**
 * Checks whether the two kangaroos can reach the same point or not.
 *
 * - T.C: O(n).
 * - S.C: O(1).
 *
 * @param {number} x1 The position of kangaroo 1.
 * @param {number} v1 The jump veolcity of kangaroo 1.
 * @param {number} x2 The position of kangaroo 2.
 * @param {number} v2 The jump veolcity of kangaroo 2.
 * @returns {"YES" | "NO"}
 */
function kangaroo(x1, v1, x2, v2) {
  let p1 = x1,
      p2 = x2,
      i = 0;

  while (i++ < MAX_ITERATIONS) {
    if (p1 === p2) return "YES";

    p1 += v1;
    p2 += v2;
  }

  return "NO";
}
----

=== Solution 2 with a math formula

Let’s say kangaroo 1 starts at position stem:[p₁] with a velocity of stem:[v₁].
After stem:[j] jumps, it will have reached a certain distance.

[stem]
++++
d = v * j
++++

That is, the distance is the velocity times the number of jumps.
This is the formula for the distance.
We are replacing time with jumps because we can assume stem:[j] jumps to be like the number of seconds, like if the kangaroos perform a jump for seconds.

So their position after a certain number of jumps is their start position plus velocity times number of jumps.
This reasoning gives us this formula:

[source,text]
====
end_position = start_position + jump_velocity * number_of_jumps
====

Or

[stem]
++++
e = s + v * j
++++

Where stem:[e] is the _end position_, stem:[s] is the start position, stem:[v] is the jump velocity and stem:[j] is the number of jumps.

Of course, we want to prove that if we apply that formula for both kangaroos, we’ll get the same result.

[stem]
++++
s₁ + (v₁ * j) = s₂ + (v₂ * j)
++++

We want to isolate stem:[j] as we want to prove that after stem:[j] jumps, both kangaroos have travelled to the same point.

Subtract stem:[s₁] from both sides:

[stem]
++++
\displaylines{
-s₁ + s₁ + (v₁ * j) = s₂ - s₁ + (v₂ * j)\\
v₁ * j = s₂ - s₁ + v₂ * j
}
++++

Then subtract stem:[v₂ * j] from both sides as a means to move stem:[j] to the left side of the equation:

[stem]
++++
\displaylines{
v₁ * j - (v₂ * j) = s₂ - s₁ + v₂ * j - (v₂ * j)\\
v₁ * j - (v₂ * j) = s₂ - s₁
}
++++

Now we can distribute stem:[j]:
[stem]
++++
j * (v₂ - v₁) = s₂ - s₁
++++

Finally, divide both sides by stem:[v₂ - v₁]:

[stem]
++++
\displaylines{
j * \frac{v₂ - v₁}{v₂ - v₁} = \frac{s₂ - s₁}{v₂ - v₁}\\
j = \frac{s₂ - s₁}{v₂ - v₁}
}
++++

Because the problem statement deals with whole jumps which map to whole integers (there is no 3.5 jump, for instance), we want to make sure that the _remainder_ of the division is zero.
That is, that the difference between their travelled distance is zero.
So, instead of the standard division, we want _modulo_ division:

[stem]
++++
j = s₂ - s₁\text{ }\%\text{ }v₂ - v₁
++++

But because we already know the start position and the jump velocity of both kangaroos, we can simply plug those in and check the remainder.
If it is zero, it means we can answer "YES" to the question asked in the problem statement.

[source,javascript]
----
/**
 * Checks whether the two kangaroos can reach the same point or not.
 *
 * - T.C: O(1).
 * - S.C: O(1).
 *
 * @param {number} x1 The position of kangaroo 1.
 * @param {number} v1 The jump velocity of kangaroo 1.
 * @param {number} x2 The position of kangaroo 2.
 * @param {number} v2 The jump velocity of kangaroo 2.
 * @returns {"YES" | "NO"}
 */
function kangaroo(x1, v1, x2, v2) {
  if (v1 <= v2) // <1>
    return "NO";

  if ((x2 - x1) % (v1 - v2) === 0) // <2>
    return "YES";

  return "NO"; // <3>
}
----

<1> Because kangaroo 2 always starts ahead of kangaroo 1, if kangaroo’s 1 jump velocity is <= kangaroo’s 2 jump velocity, then kangaroo’s 1 will never to be able to catch up with kangaroo 2.
That is the case we handle with the first `if` condition.

<2> The second `if` condition applies the formula to check if it would result in a remainder of 0 (zero), which means the both kangaroos can reach the same point after a certain number of jumps.

<3> Else, the remainder was not zero, so return "NO".
