= C Strings
// :linkcss:
// :stylesheet: asciidoctor-original-with-overrides.css
// :stylesdir: {user-home}/Projects/proghowto
:webfonts:
:icons!: font
:source-highlighter: pygments
:pygments-css: class
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:favicon: https://fernandobasso.dev/cmdline.png


== Constant Pointers vs Pointers

Two basic ways to create an array of chars or string:

[source,c]
----
// <1>
char hello[10] = "Hello";

// <2>
char *world = "World";
----

1. `hello` is a constant pointer to char.

2. This is a normal pointer.

=== Constant Pointer

Pointer arithmetic is not allowed with constant pointers:

[source,c]
----
char hello[] = "Hello";
++hello;
// ⇒ main.c:9:8: error: cannot increment value of type 'char [10]'
// ⇒   hello++;
// ⇒   ~~~~~^
----


But can change values in memory locations with constant pointer.

[source,c]
----
char hello[10] = "Hello";
hello[0] = 'X';
*(hello + 4) = 'Z';
printf("%s\n", hello);
// ⇒ XellZ
----

The pointer cannot be operated with pointer arithmetic, but the value stored the memory can be changed.

=== Pointer

With (normal) pointers, pointer arithmetic is possible:

[source,c]
----
char *world = "World";
++world;
printf("%s\n", world);
// ⇒ orld
----


But can't change the value at a give memory position. This produces a segmentation fault:

[source,c]
----
char *world = "World";
world[1] = 'X';
*(world + 1) = 'X';
// ⇒ Segmentation fault (core dumped).
----

We get segmentation fault either using subscript notation or pointer notation.


