= Docker entrypoint initdb.d shell script error
:page-subtitle:
:page-tags:
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:source-highlighter: highlight.js
:experimental:
:stem: latexmath
:toc: left
:imagesdir: __assets
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== The Initial Setup

While working on a certain project, we were using PostgreSQL in Docker.
The setup was initially done on a Linux machine.
We had this folder structure:

[source,text]
----
$ tree .
.
├── api
│   ├── foo.hs
│   ├── bar.hs
│   └── server.hs
├── docker
│   ├── docker-compose.yml
│   └── docker-entrypoint-initdb.d
│       └── 01.sh
├── main.hs
├── Makefile
└── README.adoc
----

The file `docker-compose.yml`, among other things, had this setup for the DB service:

[source,yaml]
----
services:
  db:
    image: postgres:16
    container_name: our_container
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
----

The shell script itself basically consisted of some `psql` commands to add some initial stuff to the server:

[source,sh]
----
#!/bin/bash

psql \
	-v ON_ERROR_STOP=1 \
	--username "$POSTGRES_USER" \
	--dbname admin <<-EOSQL
	CREATE ROLE $PG_DEV_USER \
	WITH \
		CREATEDB REPLICATION \
		LOGIN PASSWORD '$PG_DEV_PASSWORD' \
	VALID UNTIL 'infinity';
EOSQL

psql -v ON_ERROR_STOP=1 \
	--username "$PG_DEV_USER" \
	--dbname admin <<-EOSQL
	CREATE DATABASE ourdb WITH \
			ENCODING='UTF8' \
			OWNER=$PG_DEV_USER \
			LC_CTYPE='en_US.UTF-8' \
			LC_COLLATE='en_US.UTF-8' \
			TEMPLATE=template0 \
			CONNECTION LIMIT=3;
EOSQL

psql -v ON_ERROR_STOP=1 \
	--username "$PG_DEV_USER" \
	--dbname ourdb <<-EOSQL

CREATE TABLE users ( \
	id VARCHAR(32) PRIMARY KEY \
);

INSERT INTO users ( \
		id \
) VALUES \
('yoda'), \
('aayla'), \
('ahsoka');
EOSQL
----

== File not round error

Later, another engineer fetched the code, did some changes do `01.sh` tried ran `docker compose up` inside the `docker` directory.
The command ran, but the container failed to execute `01.sh` with a message similar to this one:

[source,text]
----
cannot execute
file not found
----

== The Solution

The problem ended up being Windows style of newlines, which uses `CRLF`, causing `bash` inside the container to fail to run the shell script.

We simply rewrote the file with Linux `LF` newlines, and then the problem was solved.
