= Docker
:page-subtitle: Containers
:page-tags: docker container linux unix
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Requirements for learning Docker

To have a good grasping of working with Docker, it is essential that we have a solid understanding of Unix (most specifically Linux) operating system, command line and shells, and also networking, and quite frankly, make related topics.
Almost everything we do with Docker ends up needing that sort of knowledge and experience.

Moreover, understanding the tools we want to run in Docker is a must as well.
For example, to run a database like PostgreSQL in Docker, besides knowing Docker and Linux and whatnot (as mentioned above), knowing how PostgreSQL itself is supposed to be managed, configured, fine tuned, etc. is important.
Understanding of PostgreSQL roles, users, replication, etc. are all part of the deal.

In short, a lot of stuff has to be understood together.

That said, there is not problem in learning on demand as we figure out other things we are still lacking.
We can research on topics as they become important or necessary on our daily routines.

== ArchLinux on MacOS m2

.Dockerfile before

[source,bash]
----
FROM --platform=linux/x86_64 archlinux:latest
CMD ["echo", "It works!"]
----

[source,text]
----
$ docker build --tag hello:latest --file ./Dockerfile1 .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  73.73kB
Step 1/3 : FROM archlinux:latest
latest: Pulling from library/archlinux
no matching manifest for linux/arm64/v8 in the manifest list entries
----

We need to specify the platform:

[source,shell-session]
----
$ docker build --tag hello:latest --file ./Dockerfile1 .

$ docker run hello:latest
WARNING: The requested image's platform (linux/amd64) does not match
the detected host platform (linux/arm64/v8) and no specific platform
was requested
It works!

docker [go-1.23.1]
$ docker run --platform=linux/x86_64 hello:latest
It works!
----

* https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8

