= Count Vowels
:page-subtitle: 7kyu Codewars Challenge
:page-tags: codewars algorithm
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Challenge

* link:https://www.codewars.com/kata/54ff3102c1bad923760001f3[Count Vowels :: Codewars 7kyu Challenge^]

== Intro

Considering the English alphabet, count the number of vowels in a string.
The input string can a mix of uppercase and lowercase characters.

== Scheme

=== Solution 1

Using string functions from srfi-13.
We use an `or` to check for both uppercase and lowercase vowels.

[source,scheme]
----
(import (only srfi-13 string-fold string-index))

;;;;
;; Count the number of vowels in s.
;;
(define (count-vowels s)
  (string-fold (lambda (c acc)
                 (if (or (string-index "aeiou" c)
                         (string-index "AEIOU" c))
                     (+ acc 1)
                     acc))
               0
               s))
----

The `string-fold` function passes a type char (not a type string) to the callback, and `string-index` takes a string and a char.

=== Solution 2

To avoid the `or` used earlier with `string-index`, we can try `string-contains-ci`.
But because `string-fold` passes chars (not strings) to the callback, we first need to convert the char to a string before comparing.

[source,scheme]
----
(import (only srfi-13 string-fold string-contains-ci))

;;;;
;; Count the number of vowels in s.
;;
(define (count-vowels s)
  (string-fold (lambda (c acc)
                 (if (string-contains-ci "aeiou" (string c))
                     (+ acc 1)
                     acc))
               0
               s))
----

== Go

=== Unit Tests

[source,go]
----
import "testing"

func TestCountVowels(t *testing.T) {
  t.Run("empty string", func(t *testing.T) {
    got := CountVowels("")
    want := 0

    if got != want {
      t.Errorf("got count of %d, want count of %d", got, want)
    }
  })

  t.Run("string with no wowels", func(t *testing.T) {
    got := CountVowels("_xyz_ !")
    want := 0

    if got != want {
      t.Errorf("got count of %d, want count of %d", got, want)
    }
  })

  t.Run("string with a few vowels", func(t *testing.T) {
    got := CountVowels("ab cd ef")
    want := 2

    if got != want {
      t.Errorf("got count of %d, want count of %d", got, want)
    }
  })

  t.Run("string with only vowels", func(t *testing.T) {
    got := CountVowels("aAeEiIoOuU")
    want := 10

    if got != want {
      t.Errorf("got count of %d, want count of %d", got, want)
    }
  })
}
----

=== Solution 1 with strings.Contains()

[source,go]
----
import "strings"

const VOWELS = "AEIOUaeiou"

// CountVowels counts the number of uppercase and lowercase vowels from
// the English alphabet.
//
// ASSUME: "y" is not considered a vowel for this exercise.
func CountVowels(str string) (count int) {
	count = 0

	for _, c := range str {
		if strings.Contains(VOWELS, string(c)) {
			count++
		}
	}

	return count
}
----

=== Solution 2 with switch case

This approach uses no package besides vanilla language features.

[source,go]
----
// CountVowels counts the number of uppercase and lowercase vowels from
// the English alphabet.
//
// ASSUME: "y" is not considered a vowel for this exercise.
func CountVowels(str string) (count int) {
	count = 0

	for _, chr := range str {
		switch chr {
		case 'a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U':
			count++
		}
	}

	return count
}
----
