= Help

== Running the tests

To run the tests run the command `go test` from within the exercise directory.

If the test suite contains benchmarks, you can run these with the `--bench` and `--benchmem` flags:

 go test -v --bench . --benchmem

Keep in mind that each reviewer will run benchmarks on a different machine, with different specs, so the results from these benchmark tests may vary.

== Submitting your solution

You can submit your solution using the `exercism submit animal_magic.go` command.
This command will upload your solution to the Exercism website and print the solution page's URL.

It's possible to submit an incomplete solution which allows you to:

* See how others have completed the exercise
* Request help from a mentor

== Need to get help?

If you'd like help solving the exercise, check the following pages:

* The https://exercism.org/docs/tracks/go[Go track's documentation]
* The https://forum.exercism.org/c/programming/go[Go track's programming category on the forum]
* https://forum.exercism.org/c/programming/5[Exercism's programming category on the forum]
* The https://exercism.org/docs/using/faqs[Frequently Asked Questions]

Should those resources not suffice, you could submit your (incomplete) solution to request mentoring.

To get help if you're having trouble, you can use one of the following resources:

* https://golang.org/doc/code.html[How to Write Go Code]
* https://golang.org/doc/effective_go.html[Effective Go]
* http://golang.org/help[Go Resources]
* http://stackoverflow.com/questions/tagged/go[StackOverflow]
