= Arrays
:page-subtitle: go
:page-tags: go programming-language array
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Basic

An array is a numbered sequence of elements of a specific length.
That is, the type of the array encodes the type of the array constituents _and_ the length.
In other words, the array's length is part of the type of the array (like tuples Haskell or TypeScript).

Declare an array of two `int` elements:

[source,go]
----
var xs [2]int

fmt.Println(len(xs))
//=> 2

fmt.Println(xs)
//=> [0 0]
----

`xs` above was not initialized to any values, so it is _zero-valued_, which of `int` means ``0``s.

[NOTE]
====
Note the array is printed inside a pair of square brackets.
====

And then we can assign values by using indexes:

[source,go]
----
var xs [2]int
fmt.Println(len(xs))
//=> 2

xs[0] = 10
xs[1] = 20

fmt.Println(xs)
//=> [10, 20]
----

And it is an error trying to assign or read out bounds of the array indexes:

[source,go]
----
var xs [2]int
xs[3] = 1
// Error:
// invalid argument: index 3 out of bounds [0:2]

fmt.Println(xs[5])
// Error:
// invalid argument: index 5 out of bounds [0:2]
----

It is possible to let the compiler count the number of elements when declaring and initializing:

[source,go]
----
var xs = [...]int{10, 20}
var ys = [...]int{10, 20, 30}
----

And even if we type the array variables on the left side of the assignment operator, it is still required to type the “braces composite literal” initialization on the right side too!

[source,go]
----
var xs [2]int = [...]int{10, 20}
var ys [3]int = [...]int{10, 20, 30}

// Same as:
var xs [2]int = [2]int{10, 20}
var ys [3]int = [3]int{10, 20, 30}
----

And make sure the number of elements on the left (inside `[]`) matches the actual number of elements on the right.

== The index: syntax

If specifics indexes are assigned values with the `idx:` syntax, elements in between are zeroed:

[source,go]
----
var xs [5]int = [...]int{100, 3: 400, 500}
fmt.Println(xs)
//=> [100 0 0 400 500]
----

But after the `idx:` syntax, we have to fill in the rest to match the length or we'll get an error:

[source,go]
----
var xs [5]int = [...]int{100, 3: 400 }
fmt.Println(xs)
// Error: cannot use [...]int{…} (value of type [4]int) as [5]int
// value in variable declaration
----

Here we have 100 for index 0, index 1 and 2 get zeroed, and we explicitly use the `idx:` syntax to assign the value 400 to index 3.
But the compiler *does NOT* apply the zero-value to index 4 and thus we get an error.
When using the `idx:` syntax, we must make sure all the remaining positions (if any) are correctly provided the expected values.
Only values _in between_ get zero-valued.
