= Go Unit Testing
:page-subtitle: Go
:page-tags: go unit-tests
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:source-highlighter: highlight.js
:experimental:
:stem: latexmath
:toc: left
:imagesdir: __assets
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


== Introduction to unit testing in Go

Go ships with the 'testing' package.
Example:

.hello_test.go
[source,go]
----
package hello

import "testing"

func TestHelloWorld(t *testing.T) {
	expected := "Hello, World!"
	if observed := HelloWorld(); observed != expected {
		t.Fatalf("HelloWorld() = %v, want %v", observed, expected)
	}
}
----

[NOTE]
====
Make sure to end your file name with `_test.go`.
Read `go help test` for details.
====

Then run with:

[source,shell-session]
----
$ go test
----

Or test a specific package:

[source,shell-session]
----
$ go test hello
----

Or using the `-v` flag to also the list of tests descriptors:

[source,shell-session]
----
$ go test -v
$ go test -v hello
----

Or to run tests that match a specific description, use `-run <description>`:

[source,shell-session]
----
$ go test -v -cover -run 'Triangle'
----

=== References

* https://pkg.go.dev/testing
* https://ieftimov.com/posts/testing-in-go-subtests/

== Subtests (or subcases) leaking state?

Consider testing a counter singleton with a test file like this one:

[source,go]
----
package singleton

import "testing"

func TestGetInstance(t *testing.T) {
	t.Run("create instance correctly", func(t *testing.T) {
		counter := GetInstance()

		if counter == nil {
			t.Error("Expected Singleton instance, got nil")
		}
	})

	t.Run("always returns he same reference", func(t *testing.T) {
		ref1 := GetInstance()
		ref2 := GetInstance()

		if ref1 != ref2 {
			t.Error("Counters are not the same reference to the same instance")
		}
	})

	t.Run("returns correct value on first call", func(t *testing.T) {
		count := GetInstance().AddOne()

		if count != 1 {
			t.Errorf("Want 1 for first call, got %d", count)
		}
	})

	t.Run("returns correct value on each subsequent call", func(t *testing.T) {
		counter := GetInstance()

		_ = counter.AddOne()
		valueForCall2 := counter.AddOne()

		if valueForCall2 != 2 {
			t.Errorf("Want 2 for second call, got %d", valueForCall2)
		}
	})
}
----

Basically, `GetInstance()` returns an instance of a counter singleton, and each time `AddOne()` is invoked on that instance, it increments and returns the next value of the counter.

But the last subtest fails because the value of the counter is 3, not 2!

And the problem is that the previous subtest invokes `AddOne()` once, and value of counter in the next subtest already starts at 1 (not 0).

This is not a problem with the singleton itself, which is supposed to be shared anyway (“Hey, that is what a singleton should do, right?”), but they way tests and subtests work in Go.
The tests and subtests *do not* run like if they were individual programs (like in some other testing libraries in other languages).
In the tests above, `counter`, `ref1` and `ref2` are all the same reference even though they are on their own blocks.
