= Number Line Jumps (Kangaroo)
:page-subtitle: HackerRank
:page-tags: hackerrank algorithm loop math
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:imagesdir: __assets
:stem: latexmath
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

tags: hackerrank algorithm number loop math formula

* link:https://www.hackerrank.com/challenges/kangaroo/problem[Number Line Jumps (Kangaroo) challenge on HackerRank^].

At after some number of jumps, they either get to the same location (return "YES"), or they exceed the number of jumps and never get to the same location together (return "NO").

The kangaroos will both perform the same number of jumps.
One kangaroo cannot perform more or less jumps than the other.

One of the constraints states that the second kangaroos start position will always be greater than the first kangaroo.
That is, the first kangaroo always starts behind the second, and the second kangaroo always starts ahead of the first.

== JavaScript

=== Solution 1 with a loop

This solution involves looping through the jumps to test if we can arrive at the same location at some point.

Because it uses a loop, it has T.C stem:[O(1)].

[source,javascript]
----
const MAX_ITERATIONS = 1e4;

/**
 * Checks whether the two kangaroos can reach the same point or not.
 *
 * - T.C: O(n).
 * - S.C: O(1).
 *
 * @param {number} x1 The position of kangaroo 1.
 * @param {number} v1 The jump veolcity of kangaroo 1.
 * @param {number} x2 The position of kangaroo 2.
 * @param {number} v2 The jump veolcity of kangaroo 2.
 * @returns {"YES" | "NO"}
 */
function kangaroo(x1, v1, x2, v2) {
  let p1 = x1,
      p2 = x2,
      i = 0;

  while (i++ < MAX_ITERATIONS) {
    if (p1 === p2) return "YES";

    p1 += v1;
    p2 += v2;
  }

  return "NO";
}
----

=== Solution 2 with a math formula

Let's say kangaroo 1 starts at position stem:[p1], with a velocity of v1, and will make stem:[j] jumps.

[source,javascript]
----
/**
 * Checks whether the two kangaroos can reach the same point or not.
 *
 * - T.C: O(1).
 * - S.C: O(1).
 *
 * @param {number} x1 The position of kangaroo 1.
 * @param {number} v1 The jump veolcity of kangaroo 1.
 * @param {number} x2 The position of kangaroo 2.
 * @param {number} v2 The jump veolcity of kangaroo 2.
 * @returns {"YES" | "NO"}
 */
function kangaroo(x1, v1, x2, v2) {
  if (v1 <= v2)
    return "NO";

  if ((x2 - x1) % (v1 - v2) === 0)
    return "YES";

  return "NO";
}
----

Because kangaroo 2 always starts ahead of kangaroo 1, if kangaroo's 1 jump velocity is <= kangaroo's 2 jump velocity, then kangaroo's 1 will never to be able to catch up with kangaroo 2.
That is the case we handle with the first `if` condition.

The second `if` condition applies the formula to check if it would result in a remainder of 0 (zero), which means the both kangaroos can reach the same point after a certain number of jumps.

Else, the remainder was not zero, so return "NO".
