
== Functions


=== exit vs return

`exit` can be used in scripts and in functions. In both cases, it causes _exiting_ from the script.

`return` can be used to exist a function. Both `exist` and `return` accept a number which acts as the exit status for the function or script.

[source,bash,lineos]
----
function greet () {
  printf '%s\n' 'Hello!' # <1>
}

greet # <2>

echo $? # <3>
----

1. The `greet` function prints a simple text. `printf` returns 0, meaning “success”, that is, “the printf command was executed successfully.”

2. Invoke the function greet. Because it does not provide an explicit return value, it returns the exist status of the last command.

3. `$?` contains the exist status of the last command, in this case, the return/exist status of the `greet` invocation.

==== exit inside a function

[source,bash,lineos]
----
function greet () {
  printf '%s\n' 'Hello'
  exit 1 # <1>
  echo 'world'
}

greet

echo 'The Force'
----

1. Prints “Hello”, exits with 1, and does not even print “world”. Even though `exit` was used inside the function, it exits from the entire script itself. That is why we never reach the line `echo 'The Force'` either.



